name: Test and deployment pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]     

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: npm install 
        run: npm install 
      - name: lint 
        run: npm run lint
      - name: run build
        run: npm run build
      - name: run test
        run: npm run test 
        env: 
          TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
      - name: heroku deploy
        if: ${{github.event_name == 'push'}}
        uses: akhileshns/heroku-deploy@v3.9.9 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "bloglistci" #Must be unique in Heroku
          heroku_email: "laura.a.byman@gmail.com"
          checkstring: "ok"
          healthcheck: "https://bloglistci.herokuapp.com//health"
          rollbackonhealthcheckfailed: true
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }}
        uses: anothrNick/github-tag-action@1.33.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
      # - name: notify slack if failure
      #   uses: 8398a7/action-slack@v3
      #   if: ${{ failure() }}
      #   with:
      #     status: failure
      #     fields: repo, message, commit, author, took # selectable (default: repo,message)
      #   env:
      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
      # - name: notify slack if success
      #   uses: 8398a7/action-slack@v3
      #   if: ${{ success()  && github.event_name == 'push'}}
      #   with:
      #     status: custom
      #     fields: commit,author,took
      #     custom_payload: |
      #       {
      #         attachments: [{
      #           text: `a new version deployed to https://https://bloglistci.herokuapp.com/.herokuapp.com (${process.env.AS_COMMIT})
      #           by ${process.env.AS_AUTHOR}, build took ${process.env.AS_TOOK}`,
      #         }]
      #       }
      #   env:
      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required

        
